name: Deploy to Render

on:
  schedule:
    - cron: "*/60 * * * *"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Render
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_DEPLOY_KEY }}
        run: curl -X POST "https://api.render.com/deploy/srv-cnd1906n7f5s73bjdh9g?key=${RENDER_API_KEY}"
